# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldmap', '0002_auto_20180416_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='airportCode',
            field=models.CharField(default='OMA', max_length=10),
            preserve_default=False,
        ),
    ]
