# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldmap', '0003_location_airportcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locationName', models.CharField(max_length=200)),
                ('searches', models.IntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='worldmap.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='locationvisitors',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locationvisitors',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='LocationVisitors',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
